# Generated by Django 5.2.17 on 2026-09-14 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_customertoken'),
        ('transactions', '0002_transaction_customer_walletsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='accounts.customer')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='idempotency_key', to='transactions.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'key'), name='unique_idempotency_key_per_customer')],
            },
        ),
    ]
