# Generated by Django 5.1.5 on 2026-09-14 18:20

import apps.transactions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.transactions.models.make_reference, editable=False, max_length=32, unique=True)),
                ('state', models.CharField(choices=[('created', 'Cree'), ('awaiting_payment', 'Attente paiement'), ('payment_confirmed', 'Paiement confirme'), ('payout_queued', 'File de decaissement'), ('payout_in_flight', 'Decaissement en cours'), ('payout_unknown', 'Decaissement indetermine'), ('payout_pending', 'Decaissement en attente operateur'), ('completed', 'Terminee'), ('payment_expired', 'Paiement expire'), ('payout_failed', 'Echec decaissement'), ('refunded', 'Remboursee'), ('cancelled', 'Annulee')], db_index=True, default='created', max_length=32)),
                ('source_wallet', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('kashpaw', 'Kashpaw'), ('carte', 'Carte bancaire')], max_length=16)),
                ('destination_wallet', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('kashpaw', 'Kashpaw'), ('carte', 'Carte bancaire')], max_length=16)),
                ('sender_phone', models.CharField(blank=True, max_length=16)),
                ('recipient_phone', models.CharField(max_length=16)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_in', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_out', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_platform', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_provider_id', models.CharField(blank=True, max_length=64)),
                ('payment_redirect_url', models.URLField(blank=True, max_length=500)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('poll_count', models.PositiveIntegerField(default=0)),
                ('payout_reference', models.CharField(blank=True, db_index=True, max_length=40)),
                ('payout_provider_id', models.CharField(blank=True, max_length=64)),
                ('payout_api_reference', models.CharField(blank=True, max_length=64)),
                ('payout_fee_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payout_attempts', models.PositiveIntegerField(default=0)),
                ('payout_completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=32)),
                ('to_state', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_events', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='transactions.transaction')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['state', 'created_at'], name='transaction_state_283d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recipient_phone'], name='transaction_recipie_2c8334_idx'),
        ),
    ]
