# Generated by Django 5.2.17 on 2026-09-14 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_customertoken'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.customer'),
        ),
        migrations.CreateModel(
            name='WalletSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('kashpaw', 'Kashpaw'), ('carte', 'Carte bancaire')], max_length=16, unique=True)),
                ('payment_enabled', models.BooleanField(default=False)),
                ('payout_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('wallet',),
                'constraints': [models.CheckConstraint(condition=models.Q(('payout_enabled', False), ('wallet__in', ['moncash', 'natcash']), _connector='OR'), name='payout_only_for_payout_capable_wallets')],
            },
        ),
    ]
