# Generated by Django 5.2.17 on 2026-09-14 20:31

from django.db import migrations

#: Ouverture initiale. Kashpaw et carte ne peuvent etre que sources
#: (plopplop ne decaisse que vers MonCash et NatCash).
INITIAL = {
    "moncash": (True, True),
    "natcash": (True, True),
    "kashpaw": (True, False),
    "carte": (True, False),
}


def seed(apps, schema_editor):
    WalletSetting = apps.get_model("transactions", "WalletSetting")
    for wallet, (payment, payout) in INITIAL.items():
        WalletSetting.objects.get_or_create(
            wallet=wallet, defaults={"payment_enabled": payment, "payout_enabled": payout}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_customer_walletsetting'),
    ]

    operations = [
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
