# Generated by Django 5.2.17 on 2026-09-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_seed_wallet_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
