# Generated by Django 5.2.17 on 2026-09-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_seed_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payout_eta_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_eta_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
