# Generated by Django 5.2.17 on 2026-09-16 22:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_customertoken'),
        ('transactions', '0007_transaction_payout_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLimitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cap', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=12)),
                ('monthly_cap', models.DecimalField(decimal_places=2, default=Decimal('200000'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'state', 'payment_confirmed_at'], name='txn_customer_window_idx'),
        ),
        migrations.AddField(
            model_name='transferlimitpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='transferlimitpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('daily_cap__gt', 0), ('monthly_cap__gte', models.F('daily_cap'))), name='monthly_cap_covers_daily_cap'),
        ),
    ]
