# Generated by Django 5.2.17 on 2026-09-17 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_customer_language'),
        ('transactions', '0009_seed_transfer_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_received', "Le bénéficiaire n'a rien reçu"), ('wrong_amount', 'Le bénéficiaire a reçu un autre montant'), ('wrong_recipient', "L'argent est parti sur un autre numéro"), ('charged_twice', "J'ai payé deux fois le même envoi"), ('other', 'Autre chose')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('answered', 'Répondue'), ('closed', 'Close')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('seen_by_customer_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_closed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='accounts.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ClaimMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_kind', models.CharField(choices=[('customer', 'Client'), ('operator', 'Operateur')], max_length=16)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_messages', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='claims.claim')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'answered'])), fields=('transaction',), name='one_active_claim_per_transaction'),
        ),
    ]
