from .base import *  # noqa: F401,F403

DEBUG = False

SECRET_KEY = env("DJANGO_SECRET_KEY", required=True)  # noqa: F405
PLOPPLOP["CLIENT_ID"] = env("PLOPPLOP_CLIENT_ID", required=True)  # noqa: F405
PLOPPLOP["CLIENT_SECRET"] = env("PLOPPLOP_CLIENT_SECRET", required=True)  # noqa: F405

OTP["BACKEND"] = "twilio"  # noqa: F405
TWILIO["ACCOUNT_SID"] = env("TWILIO_ACCOUNT_SID", required=True)  # noqa: F405
TWILIO["AUTH_TOKEN"] = env("TWILIO_AUTH_TOKEN", required=True)  # noqa: F405
TWILIO["VERIFY_SERVICE_SID"] = env("TWILIO_VERIFY_SERVICE_SID", required=True)  # noqa: F405
API_DOCS_ENABLED = env("API_DOCS_ENABLED", "0") == "1"  # noqa: F405

SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
