# Generated by Django 5.2.17 on 2026-09-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_customertoken'),
        ('transactions', '0009_seed_transfer_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS')], default='sms', max_length=16)),
                ('template', models.CharField(choices=[('transfer_completed', 'Transfert livre'), ('transfer_refunded', 'Transfert rembourse')], max_length=32)),
                ('recipient', models.CharField(blank=True, max_length=16)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'A envoyer'), ('sent', 'Envoye'), ('failed', 'Echec definitif'), ('skipped', 'Non envoye')], default='pending', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.customer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'template', 'channel'), name='one_notification_per_transaction_and_template')],
            },
        ),
    ]
