# Generated by Django 5.2.17 on 2026-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.CharField(choices=[('transfer_completed', 'Transfert livre'), ('transfer_refunded', 'Transfert rembourse'), ('claim_answered', 'Reponse a une reclamation')], max_length=32),
        ),
    ]
